"""create tables

Revision ID: a1f39d76406a
Revises: 
Create Date: 2025-11-02 21:01:20.315512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f39d76406a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commands', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commands')
    )
    op.create_table('telemetries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_speed', sa.Float(), nullable=False),
    sa.Column('distance_traveled', sa.Float(), nullable=False),
    sa.Column('energy_consumed', sa.Float(), nullable=False),
    sa.Column('average_current', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='statusstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetries')
    op.drop_table('routes')
    # ### end Alembic commands ###
