"""add route relationship to telemetry

Revision ID: effd1ab2a62c
Revises: a1f39d76406a
Create Date: 2025-11-29 23:23:35.235269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effd1ab2a62c'
down_revision: Union[str, Sequence[str], None] = 'a1f39d76406a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
